### ISSUE TITLE
Build-Module.ps1  -runTests Requires machine to be US culture. 

### ISSUE THREAD

**Issue by jhoneill** [DarqueWarrior/vsteam#360]
Steps to reproduce
------------------
On a machine which is **not** set up for US-style (least significant centralized)  date ,  create a clean directory
```powershell
git clone https://github.com/MethodsAndPractices/vsteam.git
cd .\vsteam\
.\Build-Module.ps1  -configuration Release -installDep -buildHelp -runTests
```

Expected behavior
-----------------
Build completes with only status / susccess messages. 

Actual behavior
---------------

```none

\Temp> git clone https://github.com/MethodsAndPractices/vsteam.git
Cloning into 'vsteam'...
remote: Enumerating objects: 883, done.
remote: Counting objects: 100% (883/883), done.
remote: Compressing objects: 100% (655/655), done.
Receiving objects: 100% (10610/10610), 4.11 MiB | 4.16 MiB/s, done.
Resolving deltas:  19% (1507/7901)eused 327 (delta 217), pack-reused 9727R
Resolving deltas: 100% (7901/7901), done.
Temp>cd .\vsteam\
vsteam>.\Build-Module.ps1  -configuration Release -installDep -buildHelp -runTests #-skipLibBuild
Processing: types => vsteam.types.ps1xml
Processing: formats => vsteam.format.ps1xml
Processing: functions => vsteam.functions.ps1
Processing: External help file


    Directory: C:\xxxxxxx\Temp\vsteam\.docs\..

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          05/10/2020    09:30                docs
Publishing: About help files
Publishing: Manifest file
  Updating: Functions To Export
  Building: C# project (Release config)
Publishing: Complete to C:\Users\P10506111\Temp\vsteam\dist
   Testing: C# project (unit)
Test Run Failed.
Test run for C:\xxxxxxx\Temp\vsteam\Tests\library\bin\Release\netcoreapp3.1\vsteam-lib.Test.dll(.NETCoreApp,Version=v3.1)
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  X MoveProperties_StringToDateTime [70ms]
  Error Message:
   Assert.AreEqual failed. Expected:<8/27/2020 10:37:32 AM>. Actual:<27/08/2020 10:37:32>.
  Stack Trace:
     at vsteam_lib.Test.CommonTests.MoveProperties_StringToDateTime() in C:\xxxxxxxx\Temp\vsteam\Tests\library\CommonTests.cs:line 36

  X BuildDefinition_Constructor_2017_Git [19ms]
  Error Message:
   Assert.AreEqual failed. Expected:<8/23/2020 3:12:41 PM>. Actual:<23/08/2020 15:12:41>. CreatedOn
  Stack Trace:
     at vsteam_lib.Test.Provider.BuildDefinitionTests.BuildDefinition_Constructor_2017_Git() in C:\xxxxxx\Temp\vsteam\Tests\library\Provider\BuildDefinitionTests.cs:line 39

  X BuildDefinition_Constructor_2017_Tfvc [33ms]
  Error Message:
   Assert.AreEqual failed. Expected:<8/23/2020 10:30:31 PM>. Actual:<23/08/2020 22:30:31>. CreatedOn


>>>> Repeats for more files cut to save space <<<< 


Total tests: 142
     Passed: 125
     Failed: 17
 Total time: 9.7360 Seconds
C:\Program Files\dotnet\sdk\3.1.401\Microsoft.TestPlatform.targets(32,5): error MSB4181: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task returned false but did not log an error. [C:\Users\P10506111\Temp\vsteam\Tests\library\vsteam-lib.Test.csproj]

   Testing: Functions (unit)
```

Environment data
----------------

OS

- [ ] macOS
- [X] Windows
- [ ] Linux

Server

- [ ] TFS 2017
- [ ] TFS 2018
- [ ] Azure DevOps Server
- [ ] Azure DevOps Service

n/a haven't tried to logon with this build 

 $VSTeamVersionTable  is not set (even on build from gallery)
```powershell
> Get-VSTeamAPIVersion
```
n/a haven't tried to logon with this build 

Git version info
```
49d5c7f (HEAD -> trunk, tag: v7.1.1, origin/trunk, origin/HEAD) Fixed a bug in Test-VSTeamYamlPipeline (#359)
07a284a (tag: v7.1.0) Added Update-VSTeamNuGetPackageVersion (#358)
a2a8722 Added Get-VSTeampackageVersion (#357)
8c9094c Added Show-VSTeamPackage (#356)
cdc2074 Add Get-VSTeamPackage (#355)
280a320 Changing master to trunk
```

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SebastianSchuetze** [comment]
looks like this has been fixed long ago. Gonna close this.
