### ISSUE TITLE
gulp makeMarkdownJSONFile throws

### ISSUE THREAD

**Issue by CodedBeard** [DarqueWarrior/vsteam#47]
I'm guessing this is being caused by the version of Node, but I can't find one that works.

**Repro steps**
On a clean machine (tried Windows 10 and Ubuntu 16.10) which has not previously had node installed, install a new version of node, I've tried:
* 4.x latest
* 5.x latest
* 6.x latest
* 8.x latest

clone this repo
run npm install
run gulp makeMarkdownJSONFile

**Expected results**
the markdown.json file is generated

**Actual results**
```
Using gulpfile F:\src\vsteam\gulpfile.js
 Starting 'makeMarkdownJSONFile'...
 Finished 'makeMarkdownJSONFile' after 3.74 ms
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:221:7)
    at DestroyableTransform.saveFile [as _transform] (F:\src\vsteam\node_modules\vinyl-fs\lib\dest\index.js:36:26)
    at DestroyableTransform.Transform._read (F:\src\vsteam\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (F:\src\vsteam\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (F:\src\vsteam\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (F:\src\vsteam\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (F:\src\vsteam\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at DestroyableTransform.ondata (F:\src\vsteam\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at emitOne (events.js:116:13)
```

**Comment by DarqueWarrior** [comment]
Thanks for reporting this. I actually never finished this gulp file and committed by mistake. I will remove it. Sorry for the trouble.
